"""fix foreign key on article

Revision ID: 13bdedc2209c
Revises: 31dfcd5739f1
Create Date: 2022-01-07 20:43:17.023971

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13bdedc2209c'
down_revision = '31dfcd5739f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'articles', 'categories', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'articles', type_='foreignkey')
    # ### end Alembic commands ###
