"""Add realease data column in project

Revision ID: 1d4421a3c0de
Revises: 7bcc79d120e9
Create Date: 2022-01-07 21:13:13.875976

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d4421a3c0de'
down_revision = '7bcc79d120e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('release_date', sa.Date(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'release_date')
    # ### end Alembic commands ###
