"""Edit education model

Revision ID: 9746e1228119
Revises: 620948ac1eff
Create Date: 2022-01-09 16:40:35.931485

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9746e1228119'
down_revision = '620948ac1eff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('educations', sa.Column('begin_date', sa.Date(), nullable=False))
    op.add_column('educations', sa.Column('end_date', sa.Date(), nullable=False))
    op.drop_column('educations', 'duration')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('educations', sa.Column('duration', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_column('educations', 'end_date')
    op.drop_column('educations', 'begin_date')
    # ### end Alembic commands ###
