"""Edit Skill Model

Revision ID: bd38df60133b
Revises: 1d4421a3c0de
Create Date: 2022-01-08 14:55:33.205734

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd38df60133b'
down_revision = '1d4421a3c0de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('skills', sa.Column('icon', sa.String(length=10000), nullable=True))
    op.add_column('skills', sa.Column('is_icon_svg', sa.Boolean(), nullable=False))
    op.drop_column('skills', 'image_path')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('skills', sa.Column('image_path', sa.VARCHAR(length=250), autoincrement=False, nullable=True))
    op.drop_column('skills', 'is_icon_svg')
    op.drop_column('skills', 'icon')
    # ### end Alembic commands ###
