"""tag coloumn change name

Revision ID: d19816f1fa00
Revises: 7c8925c45417
Create Date: 2022-01-13 14:58:44.658491

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd19816f1fa00'
down_revision = '7c8925c45417'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tags', sa.Column('name', sa.String(length=20), nullable=False))
    op.drop_column('tags', 'tag')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tags', sa.Column('tag', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.drop_column('tags', 'name')
    # ### end Alembic commands ###
