"""edit skill icon not null

Revision ID: ff8aca2e634f
Revises: bd38df60133b
Create Date: 2022-01-08 14:59:42.848264

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff8aca2e634f'
down_revision = 'bd38df60133b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('skills', 'icon',
               existing_type=sa.VARCHAR(length=10000),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('skills', 'icon',
               existing_type=sa.VARCHAR(length=10000),
               nullable=True)
    # ### end Alembic commands ###
